"use client";
import { useEffect, useState } from "react";
import { Sidebar } from "@/components/sidebar";
import { Users, Receipt, TrendingUp, Plus, ArrowUpLeft } from "lucide-react";

type Lead = { id:string; name:string; phone:string|null; status:string; opportunity?: { amount:string|number; stage:string }|null };
const stages = [{ key:"NEW", label:"جديد" }, { key:"CONTACTED", label:"تم التواصل" }, { key:"OPPORTUNITY", label:"فرصة" }, { key:"REJECTED", label:"مرفوض" }];
export default function Dashboard() { const [leads,setLeads]=useState<Lead[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{ fetch("/api/leads").then(r=>r.ok?r.json():Promise.reject()).then(setLeads).catch(()=>setError("تعذر الاتصال بقاعدة البيانات")).finally(()=>setLoading(false)); },[]);
 const update=(id:string,status:string)=>{ setLeads(x=>x.map(l=>l.id===id?{...l,status}:l)); fetch(`/api/leads/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})}); };
 return <div className="flex min-h-screen"><Sidebar/><main className="min-w-0 flex-1 p-5 md:p-8"><header className="mb-8 flex items-center justify-between"><div><p className="text-sm text-slate-500">الأحد، 28 سبتمبر 2026</p><h1 className="mt-1 text-2xl font-bold">مرحباً بك في لوحة التحكم 👋</h1></div><button className="flex items-center gap-2 rounded-xl bg-[#0f172a] px-4 py-3 text-sm font-semibold text-white hover:bg-slate-700"><Plus size={18}/> إضافة فرصة</button></header>
 <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["مبيعات اليوم","0 دج","+0%",Receipt],["الفرص النشطة",String(leads.filter(x=>x.status!=="REJECTED").length),"هذا الشهر",TrendingUp],["عملاء محتملون",String(leads.length),"الإجمالي",Users],["معدل التحويل","0%","هذا الشهر",ArrowUpLeft]].map(([label,value,sub,Icon])=><div key={String(label)} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><Icon size={20} className="text-[#c9a961]"/></div><div className="text-2xl font-bold">{value}</div><div className="mt-2 text-xs text-slate-400">{sub}</div></div>)}</section>
 <section className="mt-8 rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><h2 className="font-bold">مسار المبيعات</h2><a href="/leads" className="text-sm text-[#9b7d39]">عرض الكل</a></div>{error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading?<p className="py-10 text-center text-slate-400">جار التحميل...</p>:<div className="grid gap-4 overflow-x-auto md:grid-cols-4">{stages.map(stage=><div key={stage.key} onDragOver={e=>e.preventDefault()} onDrop={e=>{const id=e.dataTransfer.getData("id");if(id)update(id,stage.key)}} className="min-h-48 rounded-xl bg-slate-50 p-3"><h3 className="mb-3 text-sm font-semibold">{stage.label}<span className="mr-2 rounded-full bg-slate-200 px-2 py-0.5 text-xs">{leads.filter(l=>l.status===stage.key).length}</span></h3><div className="space-y-2">{leads.filter(l=>l.status===stage.key).map(lead=><div draggable onDragStart={e=>e.dataTransfer.setData("id",lead.id)} key={lead.id} className="cursor-grab rounded-lg border bg-white p-3 shadow-sm"><p className="font-semibold">{lead.name}</p><p className="mt-1 text-xs text-slate-500">{lead.phone||"بدون هاتف"}</p></div>)}</div></div>)}</div>}</div></section></main></div>; }
